services:
  db:
    image: postgres:16-alpine
    container_name: task-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build:
      context: ./Backend
    container_name: task-api-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./Backend/.env
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tasksdb
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  postgres_data:
